# # Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


import time

def run():
    fib_seq = [1, 2]
    total = 2 # sum manually 2 as it's an even number
    
    while True:
        new_number = int(fib_seq[-2] + fib_seq[-1])
        
        if new_number <= 4000000:
            fib_seq.append(new_number)            
            if new_number % 2 == 0:
                total += new_number

        else:
            break
    
    print(f"Fibonacci sequence under four million:\n{fib_seq}\n")
    print("Answer:", total)


if __name__ == "__main__":
    startTime = time.time()
    run()
    print (f"\nThe script took {round(time.time() - startTime, 2)} seconds.")