# # Problem 12

# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

import math
import time
import sys
sys.path.append("../..")
from utils.log import MarkdownLogger
<<<<<<< HEAD

=======
>>>>>>> 88882ab8699a1600a8c57989e958aa5433687bcc

def run():
    max_divisors = 500
    n, curr_divisors = 0, 0

    while curr_divisors < max_divisors:
        n += 1
        triangle = int((n * (n + 1)) / 2)
        print(f"{triangle}...")
        curr_divisors = 0
        for divisor in range(1, int(math.sqrt(triangle) + 1)):
            if triangle % divisor == 0:
                if divisor == math.sqrt(triangle):
                    curr_divisors += 1  #for square numbers
                else:
                    curr_divisors += 2  # divisors come in pairs

<<<<<<< HEAD
    print(f"answer: {triangle}")
    return triangle
=======
    print("Answer:", answer)
    return answer
>>>>>>> 88882ab8699a1600a8c57989e958aa5433687bcc


if __name__ == "__main__":
    logger = MarkdownLogger(last_problem=723)
    problem_id = int(sys.argv[0].split("m")[1].split(".")[0])
    startTime = time.time()
    solution = run()
    duration = round(time.time() - startTime, 5)
    logger.add_problem(solution, problem_id=problem_id, duration=duration, language="Python")
    print(f"\nThe script took {round(duration, 2)} seconds.")